using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Diagnostics;

namespace DocumentationGenerator
{
    internal class Program
    {
        private static void Main()
        {
            var config = new Dictionary<string, string>();
            foreach (var x in File.ReadAllLines("config.ini"))
                config.Add($"%{x.Split('=')[0].Trim()}%", x.Split('=')[1].Trim());

            var doxy = File.ReadAllText("doxyTemp.ini");
            foreach (var conf in config)
                doxy = doxy.Replace(conf.Key, conf.Value);
            const string doxyPath = "doxy.ini";
            File.WriteAllText(doxyPath, doxy);

            var process = Process.Start(new ProcessStartInfo
            {
                FileName = "doxygen.exe",
                Arguments = doxyPath,
                CreateNoWindow = true,
                RedirectStandardOutput = true,
                UseShellExecute = false
            });

            if (process == null)
                return;

            string line;
            while ((line = process.StandardOutput.ReadLine()) != null)
                Console.WriteLine(line);

            process.WaitForExit();

            File.Delete(doxyPath);

            foreach (var html in Directory.GetFiles("html\\", "*.html"))
            {
                var data = File.ReadAllText(html);
                data = data.Replace("<li class=\"footer\">Generated by <a href=\"https://www.doxygen.org/index.html\"><img class=\"footer\" src=\"doxygen.svg\" width=\"104\" height=\"31\" alt=\"doxygen\"/></a> 1.9.3 </li>", $"<li class=\"footer\">Copyright ©2022 {config["%Company_Name%"]}</li>");
                File.WriteAllText(html, data);
            }

            File.WriteAllText("html/index.html", File.ReadAllText("html/index.html").Replace("<div class=\"contents\">\n</div>", File.ReadAllText("main_content.html")));

            if(config.TryGetValue("%Debug%", out var d) && bool.TryParse(d, out var b) && b)
                Console.ReadLine();
        }
    }
}
